package spell

import (
	"database/sql"
)

type SpellsNew struct {
	Id                   string         `db:"id"`                   // int(11) NOT NULL DEFAULT '0',
	Name                 sql.NullString `db:"name"`                 // varchar(64) DEFAULT NULL,
	Player_1             string         `db:"player_1"`             // varchar(64) DEFAULT 'BLUE_TRAIL',
	Teleport_zone        sql.NullString `db:"teleport_zone"`        // varchar(64) DEFAULT NULL,
	You_cast             sql.NullString `db:"you_cast"`             // varchar(120) DEFAULT NULL,
	Other_casts          sql.NullString `db:"other_casts"`          // varchar(120) DEFAULT NULL,
	Cast_on_you          sql.NullString `db:"cast_on_you"`          // varchar(120) DEFAULT NULL,
	Cast_on_other        sql.NullString `db:"cast_on_other"`        // varchar(120) DEFAULT NULL,
	Spell_fades          sql.NullString `db:"spell_fades"`          // varchar(120) DEFAULT NULL,
	Range                string         `db:"range"`                // int(11) NOT NULL DEFAULT '100',
	Aoerange             string         `db:"aoerange"`             // int(11) NOT NULL DEFAULT '0',
	Pushback             string         `db:"pushback"`             // int(11) NOT NULL DEFAULT '0',
	Pushup               string         `db:"pushup"`               // int(11) NOT NULL DEFAULT '0',
	Cast_time            string         `db:"cast_time"`            // int(11) NOT NULL DEFAULT '0',
	Recovery_time        string         `db:"recovery_time"`        // int(11) NOT NULL DEFAULT '0',
	Recast_time          string         `db:"recast_time"`          // int(11) NOT NULL DEFAULT '0',
	Buffdurationformula  string         `db:"buffdurationformula"`  // int(11) NOT NULL DEFAULT '7',
	Buffduration         string         `db:"buffduration"`         // int(11) NOT NULL DEFAULT '65',
	AEDuration           string         `db:"AEDuration"`           // int(11) NOT NULL DEFAULT '0',
	Mana                 string         `db:"mana"`                 // int(11) NOT NULL DEFAULT '0',
	Effect_base_value1   string         `db:"effect_base_value1"`   // int(11) NOT NULL DEFAULT '100',
	Effect_base_value2   string         `db:"effect_base_value2"`   // int(11) NOT NULL DEFAULT '0',
	Effect_base_value3   string         `db:"effect_base_value3"`   // int(11) NOT NULL DEFAULT '0',
	Effect_base_value4   string         `db:"effect_base_value4"`   // int(11) NOT NULL DEFAULT '0',
	Effect_base_value5   string         `db:"effect_base_value5"`   // int(11) NOT NULL DEFAULT '0',
	Effect_base_value6   string         `db:"effect_base_value6"`   // int(11) NOT NULL DEFAULT '0',
	Effect_base_value7   string         `db:"effect_base_value7"`   // int(11) NOT NULL DEFAULT '0',
	Effect_base_value8   string         `db:"effect_base_value8"`   // int(11) NOT NULL DEFAULT '0',
	Effect_base_value9   string         `db:"effect_base_value9"`   // int(11) NOT NULL DEFAULT '0',
	Effect_base_value10  string         `db:"effect_base_value10"`  // int(11) NOT NULL DEFAULT '0',
	Effect_base_value11  string         `db:"effect_base_value11"`  // int(11) NOT NULL DEFAULT '0',
	Effect_base_value12  string         `db:"effect_base_value12"`  // int(11) NOT NULL DEFAULT '0',
	Effect_limit_value1  string         `db:"effect_limit_value1"`  // int(11) NOT NULL DEFAULT '0',
	Effect_limit_value2  string         `db:"effect_limit_value2"`  // int(11) NOT NULL DEFAULT '0',
	Effect_limit_value3  string         `db:"effect_limit_value3"`  // int(11) NOT NULL DEFAULT '0',
	Effect_limit_value4  string         `db:"effect_limit_value4"`  // int(11) NOT NULL DEFAULT '0',
	Effect_limit_value5  string         `db:"effect_limit_value5"`  // int(11) NOT NULL DEFAULT '0',
	Effect_limit_value6  string         `db:"effect_limit_value6"`  // int(11) NOT NULL DEFAULT '0',
	Effect_limit_value7  string         `db:"effect_limit_value7"`  // int(11) NOT NULL DEFAULT '0',
	Effect_limit_value8  string         `db:"effect_limit_value8"`  // int(11) NOT NULL DEFAULT '0',
	Effect_limit_value9  string         `db:"effect_limit_value9"`  // int(11) NOT NULL DEFAULT '0',
	Effect_limit_value10 string         `db:"effect_limit_value10"` // int(11) NOT NULL DEFAULT '0',
	Effect_limit_value11 string         `db:"effect_limit_value11"` // int(11) NOT NULL DEFAULT '0',
	Effect_limit_value12 string         `db:"effect_limit_value12"` // int(11) NOT NULL DEFAULT '0',
	Max1                 string         `db:"max1"`                 // int(11) NOT NULL DEFAULT '0',
	Max2                 string         `db:"max2"`                 // int(11) NOT NULL DEFAULT '0',
	Max3                 string         `db:"max3"`                 // int(11) NOT NULL DEFAULT '0',
	Max4                 string         `db:"max4"`                 // int(11) NOT NULL DEFAULT '0',
	Max5                 string         `db:"max5"`                 // int(11) NOT NULL DEFAULT '0',
	Max6                 string         `db:"max6"`                 // int(11) NOT NULL DEFAULT '0',
	Max7                 string         `db:"max7"`                 // int(11) NOT NULL DEFAULT '0',
	Max8                 string         `db:"max8"`                 // int(11) NOT NULL DEFAULT '0',
	Max9                 string         `db:"max9"`                 // int(11) NOT NULL DEFAULT '0',
	Max10                string         `db:"max10"`                // int(11) NOT NULL DEFAULT '0',
	Max11                string         `db:"max11"`                // int(11) NOT NULL DEFAULT '0',
	Max12                string         `db:"max12"`                // int(11) NOT NULL DEFAULT '0',
	Icon                 string         `db:"icon"`                 // int(11) NOT NULL DEFAULT '0',
	Memicon              string         `db:"memicon"`              // int(11) NOT NULL DEFAULT '0',
	Components1          string         `db:"components1"`          // int(11) NOT NULL DEFAULT '-1',
	Components2          string         `db:"components2"`          // int(11) NOT NULL DEFAULT '-1',
	Components3          string         `db:"components3"`          // int(11) NOT NULL DEFAULT '-1',
	Components4          string         `db:"components4"`          // int(11) NOT NULL DEFAULT '-1',
	Component_counts1    string         `db:"component_counts1"`    // int(11) NOT NULL DEFAULT '1',
	Component_counts2    string         `db:"component_counts2"`    // int(11) NOT NULL DEFAULT '1',
	Component_counts3    string         `db:"component_counts3"`    // int(11) NOT NULL DEFAULT '1',
	Component_counts4    string         `db:"component_counts4"`    // int(11) NOT NULL DEFAULT '1',
	NoexpendReagent1     string         `db:"NoexpendReagent1"`     // int(11) NOT NULL DEFAULT '-1',
	NoexpendReagent2     string         `db:"NoexpendReagent2"`     // int(11) NOT NULL DEFAULT '-1',
	NoexpendReagent3     string         `db:"NoexpendReagent3"`     // int(11) NOT NULL DEFAULT '-1',
	NoexpendReagent4     string         `db:"NoexpendReagent4"`     // int(11) NOT NULL DEFAULT '-1',
	Formula1             string         `db:"formula1"`             // int(11) NOT NULL DEFAULT '100',
	Formula2             string         `db:"formula2"`             // int(11) NOT NULL DEFAULT '100',
	Formula3             string         `db:"formula3"`             // int(11) NOT NULL DEFAULT '100',
	Formula4             string         `db:"formula4"`             // int(11) NOT NULL DEFAULT '100',
	Formula5             string         `db:"formula5"`             // int(11) NOT NULL DEFAULT '100',
	Formula6             string         `db:"formula6"`             // int(11) NOT NULL DEFAULT '100',
	Formula7             string         `db:"formula7"`             // int(11) NOT NULL DEFAULT '100',
	Formula8             string         `db:"formula8"`             // int(11) NOT NULL DEFAULT '100',
	Formula9             string         `db:"formula9"`             // int(11) NOT NULL DEFAULT '100',
	Formula10            string         `db:"formula10"`            // int(11) NOT NULL DEFAULT '100',
	Formula11            string         `db:"formula11"`            // int(11) NOT NULL DEFAULT '100',
	Formula12            string         `db:"formula12"`            // int(11) NOT NULL DEFAULT '100',
	LightType            string         `db:"LightType"`            // int(11) NOT NULL DEFAULT '0',
	GoodEffect           string         `db:"goodEffect"`           // int(11) NOT NULL DEFAULT '0',
	Activated            string         `db:"Activated"`            // int(11) NOT NULL DEFAULT '0',
	Resisttype           string         `db:"resisttype"`           // int(11) NOT NULL DEFAULT '0',
	Effectid1            string         `db:"effectid1"`            // int(11) NOT NULL DEFAULT '254',
	Effectid2            string         `db:"effectid2"`            // int(11) NOT NULL DEFAULT '254',
	Effectid3            string         `db:"effectid3"`            // int(11) NOT NULL DEFAULT '254',
	Effectid4            string         `db:"effectid4"`            // int(11) NOT NULL DEFAULT '254',
	Effectid5            string         `db:"effectid5"`            // int(11) NOT NULL DEFAULT '254',
	Effectid6            string         `db:"effectid6"`            // int(11) NOT NULL DEFAULT '254',
	Effectid7            string         `db:"effectid7"`            // int(11) NOT NULL DEFAULT '254',
	Effectid8            string         `db:"effectid8"`            // int(11) NOT NULL DEFAULT '254',
	Effectid9            string         `db:"effectid9"`            // int(11) NOT NULL DEFAULT '254',
	Effectid10           string         `db:"effectid10"`           // int(11) NOT NULL DEFAULT '254',
	Effectid11           string         `db:"effectid11"`           // int(11) NOT NULL DEFAULT '254',
	Effectid12           string         `db:"effectid12"`           // int(11) NOT NULL DEFAULT '254',
	Targettype           string         `db:"targettype"`           // int(11) NOT NULL DEFAULT '2',
	Basediff             string         `db:"basediff"`             // int(11) NOT NULL DEFAULT '0',
	Skill                string         `db:"skill"`                // int(11) NOT NULL DEFAULT '98',
	Zonetype             string         `db:"zonetype"`             // int(11) NOT NULL DEFAULT '-1',
	EnvironmentType      string         `db:"EnvironmentType"`      // int(11) NOT NULL DEFAULT '0',
	TimeOfDay            string         `db:"TimeOfDay"`            // int(11) NOT NULL DEFAULT '0',
	Classes1             string         `db:"classes1"`             // int(11) NOT NULL DEFAULT '255',
	Classes2             string         `db:"classes2"`             // int(11) NOT NULL DEFAULT '255',
	Classes3             string         `db:"classes3"`             // int(11) NOT NULL DEFAULT '255',
	Classes4             string         `db:"classes4"`             // int(11) NOT NULL DEFAULT '255',
	Classes5             string         `db:"classes5"`             // int(11) NOT NULL DEFAULT '255',
	Classes6             string         `db:"classes6"`             // int(11) NOT NULL DEFAULT '255',
	Classes7             string         `db:"classes7"`             // int(11) NOT NULL DEFAULT '255',
	Classes8             string         `db:"classes8"`             // int(11) NOT NULL DEFAULT '255',
	Classes9             string         `db:"classes9"`             // int(11) NOT NULL DEFAULT '255',
	Classes10            string         `db:"classes10"`            // int(11) NOT NULL DEFAULT '255',
	Classes11            string         `db:"classes11"`            // int(11) NOT NULL DEFAULT '255',
	Classes12            string         `db:"classes12"`            // int(11) NOT NULL DEFAULT '255',
	Classes13            string         `db:"classes13"`            // int(11) NOT NULL DEFAULT '255',
	Classes14            string         `db:"classes14"`            // int(11) NOT NULL DEFAULT '255',
	Classes15            string         `db:"classes15"`            // int(11) NOT NULL DEFAULT '255',
	Classes16            string         `db:"classes16"`            // int(11) NOT NULL DEFAULT '255',
	CastingAnim          string         `db:"CastingAnim"`          // int(11) NOT NULL DEFAULT '44',
	TargetAnim           string         `db:"TargetAnim"`           // int(11) NOT NULL DEFAULT '13',
	TravelType           string         `db:"TravelType"`           // int(11) NOT NULL DEFAULT '0',
	SpellAffectIndex     string         `db:"SpellAffectIndex"`     // int(11) NOT NULL DEFAULT '-1',
	Disallow_sit         string         `db:"disallow_sit"`         // int(11) NOT NULL DEFAULT '0',
	Deities0             string         `db:"deities0"`             // int(11) NOT NULL DEFAULT '0',
	Deities1             string         `db:"deities1"`             // int(11) NOT NULL DEFAULT '0',
	Deities2             string         `db:"deities2"`             // int(11) NOT NULL DEFAULT '0',
	Deities3             string         `db:"deities3"`             // int(11) NOT NULL DEFAULT '0',
	Deities4             string         `db:"deities4"`             // int(11) NOT NULL DEFAULT '0',
	Deities5             string         `db:"deities5"`             // int(11) NOT NULL DEFAULT '0',
	Deities6             string         `db:"deities6"`             // int(11) NOT NULL DEFAULT '0',
	Deities7             string         `db:"deities7"`             // int(11) NOT NULL DEFAULT '0',
	Deities8             string         `db:"deities8"`             // int(11) NOT NULL DEFAULT '0',
	Deities9             string         `db:"deities9"`             // int(11) NOT NULL DEFAULT '0',
	Deities10            string         `db:"deities10"`            // int(11) NOT NULL DEFAULT '0',
	Deities11            string         `db:"deities11"`            // int(11) NOT NULL DEFAULT '0',
	Deities12            string         `db:"deities12"`            // int(12) NOT NULL DEFAULT '0',
	Deities13            string         `db:"deities13"`            // int(11) NOT NULL DEFAULT '0',
	Deities14            string         `db:"deities14"`            // int(11) NOT NULL DEFAULT '0',
	Deities15            string         `db:"deities15"`            // int(11) NOT NULL DEFAULT '0',
	Deities16            string         `db:"deities16"`            // int(11) NOT NULL DEFAULT '0',
	Field142             string         `db:"field142"`             // int(11) NOT NULL DEFAULT '100',
	Field143             string         `db:"field143"`             // int(11) NOT NULL DEFAULT '0',
	New_icon             string         `db:"new_icon"`             // int(11) NOT NULL DEFAULT '161',
	Spellanim            string         `db:"spellanim"`            // int(11) NOT NULL DEFAULT '0',
	Uninterruptable      string         `db:"uninterruptable"`      // int(11) NOT NULL DEFAULT '0',
	ResistDiff           string         `db:"ResistDiff"`           // int(11) NOT NULL DEFAULT '-150',
	Dot_stacking_exempt  string         `db:"dot_stacking_exempt"`  // int(11) NOT NULL DEFAULT '0',
	Deleteable           string         `db:"deleteable"`           // int(11) NOT NULL DEFAULT '0',
	RecourseLink         string         `db:"RecourseLink"`         // int(11) NOT NULL DEFAULT '0',
	No_partial_resist    string         `db:"no_partial_resist"`    // int(11) NOT NULL DEFAULT '0',
	Field152             string         `db:"field152"`             // int(11) NOT NULL DEFAULT '0',
	Field153             string         `db:"field153"`             // int(11) NOT NULL DEFAULT '0',
	Short_buff_box       string         `db:"short_buff_box"`       // int(11) NOT NULL DEFAULT '-1',
	Descnum              string         `db:"descnum"`              // int(11) NOT NULL DEFAULT '0',
	Typedescnum          sql.NullInt64  `db:"typedescnum"`          // int(11) DEFAULT NULL,
	Effectdescnum        sql.NullInt64  `db:"effectdescnum"`        // int(11) DEFAULT NULL,
	Effectdescnum2       string         `db:"effectdescnum2"`       // int(11) NOT NULL DEFAULT '0',
	Npc_no_los           string         `db:"npc_no_los"`           // int(11) NOT NULL DEFAULT '0',
	Field160             string         `db:"field160"`             // int(11) NOT NULL DEFAULT '0',
	Reflectable          string         `db:"reflectable"`          // int(11) NOT NULL DEFAULT '0',
	Bonushate            string         `db:"bonushate"`            // int(11) NOT NULL DEFAULT '0',
	Field163             string         `db:"field163"`             // int(11) NOT NULL DEFAULT '100',
	Field164             string         `db:"field164"`             // int(11) NOT NULL DEFAULT '-150',
	Ldon_trap            string         `db:"ldon_trap"`            // int(11) NOT NULL DEFAULT '0',
	EndurCost            string         `db:"EndurCost"`            // int(11) NOT NULL DEFAULT '0',
	EndurTimerIndex      string         `db:"EndurTimerIndex"`      // int(11) NOT NULL DEFAULT '0',
	IsDiscipline         string         `db:"IsDiscipline"`         // int(11) NOT NULL DEFAULT '0',
	Field169             string         `db:"field169"`             // int(11) NOT NULL DEFAULT '0',
	Field170             string         `db:"field170"`             // int(11) NOT NULL DEFAULT '0',
	Field171             string         `db:"field171"`             // int(11) NOT NULL DEFAULT '0',
	Field172             string         `db:"field172"`             // int(11) NOT NULL DEFAULT '0',
	HateAdded            string         `db:"HateAdded"`            // int(11) NOT NULL DEFAULT '0',
	EndurUpkeep          string         `db:"EndurUpkeep"`          // int(11) NOT NULL DEFAULT '0',
	Numhitstype          string         `db:"numhitstype"`          // int(11) NOT NULL DEFAULT '0',
	Numhits              string         `db:"numhits"`              // int(11) NOT NULL DEFAULT '0',
	Pvpresistbase        string         `db:"pvpresistbase"`        // int(11) NOT NULL DEFAULT '-150',
	Pvpresistcalc        string         `db:"pvpresistcalc"`        // int(11) NOT NULL DEFAULT '100',
	Pvpresistcap         string         `db:"pvpresistcap"`         // int(11) NOT NULL DEFAULT '-150',
	Spell_category       string         `db:"spell_category"`       // int(11) NOT NULL DEFAULT '-99',
	Field181             string         `db:"field181"`             // int(11) NOT NULL DEFAULT '7',
	Field182             string         `db:"field182"`             // int(11) NOT NULL DEFAULT '65',
	Pcnpc_only_flag      string         `db:"pcnpc_only_flag"`      // int(11) DEFAULT '0',
	Cast_not_standing    string         `db:"cast_not_standing"`    // int(11) DEFAULT '0',
	Can_mgb              string         `db:"can_mgb"`              // int(11) NOT NULL DEFAULT '0',
	Nodispell            string         `db:"nodispell"`            // int(11) NOT NULL DEFAULT '-1',
	Npc_category         string         `db:"npc_category"`         // int(11) NOT NULL DEFAULT '0',
	Npc_usefulness       string         `db:"npc_usefulness"`       // int(11) NOT NULL DEFAULT '0',
	MinResist            string         `db:"MinResist"`            // int(11) NOT NULL DEFAULT '0',
	MaxResist            string         `db:"MaxResist"`            // int(11) NOT NULL DEFAULT '0',
	Viral_targets        string         `db:"viral_targets"`        // int(11) NOT NULL DEFAULT '0',
	Viral_timer          string         `db:"viral_timer"`          // int(11) NOT NULL DEFAULT '0',
	Nimbuseffect         string         `db:"nimbuseffect"`         // int(11) DEFAULT '0',
	ConeStartAngle       string         `db:"ConeStartAngle"`       // int(11) NOT NULL DEFAULT '0',
	ConeStopAngle        string         `db:"ConeStopAngle"`        // int(11) NOT NULL DEFAULT '0',
	Sneaking             string         `db:"sneaking"`             // int(11) NOT NULL DEFAULT '0',
	Not_extendable       string         `db:"not_extendable"`       // int(11) NOT NULL DEFAULT '0',
	Field198             string         `db:"field198"`             // int(11) NOT NULL DEFAULT '0',
	Field199             string         `db:"field199"`             // int(11) NOT NULL DEFAULT '1',
	Suspendable          string         `db:"suspendable"`          // int(11) DEFAULT '0',
	Viral_range          string         `db:"viral_range"`          // int(11) NOT NULL DEFAULT '0',
	Songcap              string         `db:"songcap"`              // int(11) DEFAULT '0',
	Field203             string         `db:"field203"`             // int(11) DEFAULT '0',
	Field204             string         `db:"field204"`             // int(11) DEFAULT '0',
	No_block             string         `db:"no_block"`             // int(11) NOT NULL DEFAULT '0',
	Field206             string         `db:"field206"`             // int(11) DEFAULT '-1',
	Spellgroup           string         `db:"spellgroup"`           // int(11) DEFAULT '0',
	Rank                 string         `db:"rank"`                 // int(11) NOT NULL DEFAULT '0',
	Field209             string         `db:"field209"`             // int(11) DEFAULT '0',
	Field210             string         `db:"field210"`             // int(11) DEFAULT '1',
	CastRestriction      string         `db:"CastRestriction"`      // int(11) NOT NULL DEFAULT '0',
	Allowrest            string         `db:"allowrest"`            // int(11) DEFAULT '0',
	InCombat             string         `db:"InCombat"`             // int(11) NOT NULL DEFAULT '0',
	OutofCombat          string         `db:"OutofCombat"`          // int(11) NOT NULL DEFAULT '0',
	Field215             string         `db:"field215"`             // int(11) DEFAULT '0',
	Field216             string         `db:"field216"`             // int(11) DEFAULT '0',
	Field217             string         `db:"field217"`             // int(11) DEFAULT '0',
	Aemaxtargets         string         `db:"aemaxtargets"`         // int(11) NOT NULL DEFAULT '0',
	Maxtargets           string         `db:"maxtargets"`           // int(11) DEFAULT '0',
	Field220             string         `db:"field220"`             // int(11) DEFAULT '0',
	Field221             string         `db:"field221"`             // int(11) DEFAULT '0',
	Field222             string         `db:"field222"`             // int(11) DEFAULT '0',
	Field223             string         `db:"field223"`             // int(11) DEFAULT '0',
	Persistdeath         string         `db:"persistdeath"`         // int(11) DEFAULT '0',
	Field225             string         `db:"field225"`             // int(11) NOT NULL DEFAULT '0',
	Field226             string         `db:"field226"`             // int(11) NOT NULL DEFAULT '0',
	Min_dist             string         `db:"min_dist"`             // float NOT NULL DEFAULT '0',
	Min_dist_mod         string         `db:"min_dist_mod"`         // float NOT NULL DEFAULT '0',
	Max_dist             string         `db:"max_dist"`             // float NOT NULL DEFAULT '0',
	Max_dist_mod         string         `db:"max_dist_mod"`         // float NOT NULL DEFAULT '0',
	Min_range            string         `db:"min_range"`            // int(11) NOT NULL DEFAULT '0',
	Field232             string         `db:"field232"`             // int(11) NOT NULL DEFAULT '0',
	Field233             string         `db:"field233"`             // int(11) NOT NULL DEFAULT '0',
	Field234             string         `db:"field234"`             // int(11) NOT NULL DEFAULT '0',
	Field235             string         `db:"field235"`             // int(11) NOT NULL DEFAULT '0',
	Field236             string         `db:"field236"`             // int(11) NOT NULL DEFAULT '0',
}
