package npc

import (
	"database/sql"
)

type NpcTypes struct {
	Id                    int64          `db:"id"`                    // int(11) NOT NULL AUTO_INCREMENT,
	Name                  string         `db:"name"`                  // text NOT NULL,
	Lastname              sql.NullString `db:"lastname"`              // varchar(32) DEFAULT NULL,
	Level                 int64          `db:"level"`                 // tinyint(2) unsigned NOT NULL DEFAULT '0',
	Race                  int64          `db:"race"`                  // smallint(5) unsigned NOT NULL DEFAULT '0',
	Class                 int64          `db:"class"`                 // tinyint(2) unsigned NOT NULL DEFAULT '0',
	Bodytype              int64          `db:"bodytype"`              // int(11) NOT NULL DEFAULT '1',
	Hp                    int64          `db:"hp"`                    // int(11) NOT NULL DEFAULT '0',
	Mana                  int64          `db:"mana"`                  // int(11) NOT NULL DEFAULT '0',
	Gender                int64          `db:"gender"`                // tinyint(2) unsigned NOT NULL DEFAULT '0',
	Texture               int64          `db:"texture"`               // tinyint(2) unsigned NOT NULL DEFAULT '0',
	Helmtexture           int64          `db:"helmtexture"`           // tinyint(2) unsigned NOT NULL DEFAULT '0',
	Size                  float64        `db:"size"`                  // float NOT NULL DEFAULT '0',
	Hp_regen_rate         int64          `db:"hp_regen_rate"`         // int(11) unsigned NOT NULL DEFAULT '0',
	Mana_regen_rate       int64          `db:"mana_regen_rate"`       // int(11) unsigned NOT NULL DEFAULT '0',
	Loottable_id          int64          `db:"loottable_id"`          // int(11) unsigned NOT NULL DEFAULT '0',
	Merchant_id           int64          `db:"merchant_id"`           // int(11) unsigned NOT NULL DEFAULT '0',
	Alt_currency_id       int64          `db:"alt_currency_id"`       // int(11) unsigned NOT NULL DEFAULT '0',
	Npc_spells_id         int64          `db:"npc_spells_id"`         // int(11) unsigned NOT NULL DEFAULT '0',
	Npc_spells_effects_id int64          `db:"npc_spells_effects_id"` // int(11) unsigned NOT NULL DEFAULT '0',
	Npc_faction_id        int64          `db:"npc_faction_id"`        // int(11) NOT NULL DEFAULT '0',
	Adventure_template_id int64          `db:"adventure_template_id"` // int(10) unsigned NOT NULL DEFAULT '0',
	Trap_template         int64          `db:"trap_template"`         // int(10) unsigned DEFAULT '0',
	Mindmg                int64          `db:"mindmg"`                // int(10) unsigned NOT NULL DEFAULT '0',
	Maxdmg                int64          `db:"maxdmg"`                // int(10) unsigned NOT NULL DEFAULT '0',
	Attack_count          int64          `db:"attack_count"`          // smallint(6) NOT NULL DEFAULT '-1',
	Npcspecialattks       int64          `db:"npcspecialattks"`       // varchar(36) NOT NULL DEFAULT '',
	Special_abilities     string         `db:"special_abilities"`     // text,
	Aggroradius           int64          `db:"aggroradius"`           // int(10) unsigned NOT NULL DEFAULT '0',
	Assistradius          int64          `db:"assistradius"`          // int(10) unsigned NOT NULL DEFAULT '0',
	Face                  int64          `db:"face"`                  // int(10) unsigned NOT NULL DEFAULT '1',
	Luclin_hairstyle      int64          `db:"luclin_hairstyle"`      // int(10) unsigned NOT NULL DEFAULT '1',
	Luclin_haircolor      int64          `db:"luclin_haircolor"`      // int(10) unsigned NOT NULL DEFAULT '1',
	Luclin_eyecolor       int64          `db:"luclin_eyecolor"`       // int(10) unsigned NOT NULL DEFAULT '1',
	Luclin_eyecolor2      int64          `db:"luclin_eyecolor2"`      // int(10) unsigned NOT NULL DEFAULT '1',
	Luclin_beardcolor     int64          `db:"luclin_beardcolor"`     // int(10) unsigned NOT NULL DEFAULT '1',
	Luclin_beard          int64          `db:"luclin_beard"`          // int(10) unsigned NOT NULL DEFAULT '0',
	Drakkin_heritage      int64          `db:"drakkin_heritage"`      // int(10) NOT NULL DEFAULT '0',
	Drakkin_tattoo        int64          `db:"drakkin_tattoo"`        // int(10) NOT NULL DEFAULT '0',
	Drakkin_details       int64          `db:"drakkin_details"`       // int(10) NOT NULL DEFAULT '0',
	Armortint_id          int64          `db:"armortint_id"`          // int(10) unsigned NOT NULL DEFAULT '0',
	Armortint_red         int64          `db:"armortint_red"`         // tinyint(3) unsigned NOT NULL DEFAULT '0',
	Armortint_green       int64          `db:"armortint_green"`       // tinyint(3) unsigned NOT NULL DEFAULT '0',
	Armortint_blue        int64          `db:"armortint_blue"`        // tinyint(3) unsigned NOT NULL DEFAULT '0',
	D_melee_texture1      int64          `db:"d_melee_texture1"`      // int(11) NOT NULL DEFAULT '0',
	D_melee_texture2      int64          `db:"d_melee_texture2"`      // int(11) NOT NULL DEFAULT '0',
	Ammo_idfile           string         `db:"ammo_idfile"`           // varchar(30) NOT NULL DEFAULT 'IT10',
	Prim_melee_type       int64          `db:"prim_melee_type"`       // tinyint(4) unsigned NOT NULL DEFAULT '28',
	Sec_melee_type        int64          `db:"sec_melee_type"`        // tinyint(4) unsigned NOT NULL DEFAULT '28',
	Ranged_type           int64          `db:"ranged_type"`           // tinyint(4) unsigned NOT NULL DEFAULT '7',
	Runspeed              float64        `db:"runspeed"`              // float NOT NULL DEFAULT '0',
	Mr                    int64          `db:"MR"`                    // smallint(5) NOT NULL DEFAULT '0',
	Cr                    int64          `db:"CR"`                    // smallint(5) NOT NULL DEFAULT '0',
	Dr                    int64          `db:"DR"`                    // smallint(5) NOT NULL DEFAULT '0',
	Fr                    int64          `db:"FR"`                    // smallint(5) NOT NULL DEFAULT '0',
	Pr                    int64          `db:"PR"`                    // smallint(5) NOT NULL DEFAULT '0',
	Corrup                int64          `db:"Corrup"`                // smallint(5) NOT NULL DEFAULT '0',
	Phr                   int64          `db:"PhR"`                   // smallint(5) unsigned NOT NULL DEFAULT '0',
	See_invis             int64          `db:"see_invis"`             // smallint(4) NOT NULL DEFAULT '0',
	See_invis_undead      int64          `db:"see_invis_undead"`      // smallint(4) NOT NULL DEFAULT '0',
	Qglobal               int64          `db:"qglobal"`               // int(2) unsigned NOT NULL DEFAULT '0',
	Ac                    int64          `db:"AC"`                    // smallint(5) NOT NULL DEFAULT '0',
	Npc_aggro             int64          `db:"npc_aggro"`             // tinyint(4) NOT NULL DEFAULT '0',
	Spawn_limit           int64          `db:"spawn_limit"`           // tinyint(4) NOT NULL DEFAULT '0',
	Attack_delay          int64          `db:"attack_delay"`          // tinyint(3) unsigned NOT NULL DEFAULT '30',
	Findable              int64          `db:"findable"`              // tinyint(4) NOT NULL DEFAULT '0',
	Str                   int64          `db:"STR"`                   // mediumint(8) unsigned NOT NULL DEFAULT '75',
	Sta                   int64          `db:"STA"`                   // mediumint(8) unsigned NOT NULL DEFAULT '75',
	Dex                   int64          `db:"DEX"`                   // mediumint(8) unsigned NOT NULL DEFAULT '75',
	Agi                   int64          `db:"AGI"`                   // mediumint(8) unsigned NOT NULL DEFAULT '75',
	Int                   int64          `db:"_INT"`                  // mediumint(8) unsigned NOT NULL DEFAULT '80',
	Wis                   int64          `db:"WIS"`                   // mediumint(8) unsigned NOT NULL DEFAULT '75',
	Cha                   int64          `db:"CHA"`                   // mediumint(8) unsigned NOT NULL DEFAULT '75',
	See_hide              int64          `db:"see_hide"`              // tinyint(4) NOT NULL DEFAULT '0',
	See_improved_hide     int64          `db:"see_improved_hide"`     // tinyint(4) NOT NULL DEFAULT '0',
	Trackable             int64          `db:"trackable"`             // tinyint(4) NOT NULL DEFAULT '1',
	Isbot                 int64          `db:"isbot"`                 // tinyint(4) NOT NULL DEFAULT '0',
	Exclude               int64          `db:"exclude"`               // tinyint(4) NOT NULL DEFAULT '1',
	Atk                   int64          `db:"ATK"`                   // mediumint(9) NOT NULL DEFAULT '0',
	Accuracy              int64          `db:"Accuracy"`              // mediumint(9) NOT NULL DEFAULT '0',
	Avoidance             int64          `db:"Avoidance"`             // mediumint(9) unsigned NOT NULL DEFAULT '0',
	Slow_mitigation       int64          `db:"slow_mitigation"`       // smallint(4) NOT NULL DEFAULT '0',
	Version               int64          `db:"version"`               // smallint(5) unsigned NOT NULL DEFAULT '0',
	Maxlevel              int64          `db:"maxlevel"`              // tinyint(3) NOT NULL DEFAULT '0',
	Scalerate             int64          `db:"scalerate"`             // int(11) NOT NULL DEFAULT '100',
	Private_corpse        int64          `db:"private_corpse"`        // tinyint(3) unsigned NOT NULL DEFAULT '0',
	Unique_spawn_by_name  int64          `db:"unique_spawn_by_name"`  // tinyint(3) unsigned NOT NULL DEFAULT '0',
	Underwater            int64          `db:"underwater"`            // tinyint(3) unsigned NOT NULL DEFAULT '0',
	Isquest               int64          `db:"isquest"`               // tinyint(3) NOT NULL DEFAULT '0',
	Emoteid               int64          `db:"emoteid"`               // int(10) unsigned NOT NULL DEFAULT '0',
	Spellscale            float64        `db:"spellscale"`            // float NOT NULL DEFAULT '100',
	Healscale             float64        `db:"healscale"`             // float NOT NULL DEFAULT '100',
	No_target_hotkey      int64          `db:"no_target_hotkey"`      // tinyint(1) unsigned NOT NULL DEFAULT '0',
	Raid_target           int64          `db:"raid_target"`           // tinyint(1) unsigned NOT NULL DEFAULT '0',
	Chesttexture          int64          `db:"chesttexture"`          // tinyint(2) NOT NULL DEFAULT '0',
	Armtexture            int64          `db:"armtexture"`            // tinyint(2) unsigned NOT NULL DEFAULT '0',
	Bracertexture         int64          `db:"bracertexture"`         // tinyint(2) unsigned NOT NULL DEFAULT '0',
	Handtexture           int64          `db:"handtexture"`           // tinyint(2) unsigned NOT NULL DEFAULT '0',
	Legtexture            int64          `db:"legtexture"`            // tinyint(2) unsigned NOT NULL DEFAULT '0',
	Feettexture           int64          `db:"feettexture"`           // tinyint(2) unsigned NOT NULL DEFAULT '0',
	Light                 int64          `db:"light"`                 // tinyint(2) unsigned NOT NULL DEFAULT '0',
	Walkspeed             float64        `db:"walkspeed"`             // float NOT NULL DEFAULT '0',
	Peqid                 int64          `db:"peqid"`                 // int(11) NOT NULL DEFAULT '0',
	Unique                int64          `db:"unique_"`               // tinyint(2) unsigned NOT NULL DEFAULT '0',
	Fixed                 int64          `db:"fixed"`                 // tinyint(2) NOT NULL DEFAULT '0',
	Combat_hp_regen       int64          `db:"combat_hp_regen"`       // int(11) NOT NULL DEFAULT '0',
	Combat_mana_regen     int64          `db:"combat_mana_regen"`     // int(11) NOT NULL DEFAULT '0',
	Aggro_pc              int64          `db:"aggro_pc"`              // tinyint(1) unsigned NOT NULL DEFAULT '0',
	Ignore_distance       float64        `db:"ignore_distance"`       // float NOT NULL DEFAULT '600',
}
